### ISSUE TITLE
NotSupportedException when using DbInjectable within a sub query

### ISSUE THREAD

**Issue by jhartmann123** [axelheer/nein-linq#11]
Hi,

A NotSupportedException is thrown by EF6 when trying to use .Any() on a DbInjectable query.

I have a query like this:
```
var foo = dbContext.Set<Foo>().ToDbInjectable();
var query = from bar in dbContext.Set<Bar>()
            where foo.Any(f => f.SomeInjectLambdaMethod())
            select bar;
```

Now it doesn't even have to contain method that should be replaced with a lambda, only the .ToDbInjectable() is enough to get the exception.

This can be simply reproduced in the following test:
NeinLinq.Tests.DbAsyncQuery.RealTest
```
[Fact]
public async Task AnyShouldSucceed()
{
    var rewriter = new Rewriter();

    var dummies = db.Dummies.ToDbInjectable();
    var query = from dummy in db.Dummies
                where dummies.Any(d => d.Id < dummy.Id)
                select dummy;
    
    var result = await query.ToListAsync();

    Assert.True(rewriter.VisitCalled);
    Assert.Equal(2, result.Count);
}
```

Full stack:
```
System.NotSupportedException
A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.
   at System.Data.Entity.Internal.ThrowingMonitor.EnsureNotEntered()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at NeinLinq.RewriteQueryable`1.GetEnumerator() in C:\Users\Johannes\Source\nein-linq\src\NeinLinq.Queryable\RewriteQueryable.cs:line 37
   at NeinLinq.RewriteQueryable`1.System.Collections.IEnumerable.GetEnumerator() in C:\Users\Johannes\Source\nein-linq\src\NeinLinq.Queryable\RewriteQueryable.cs:line 41
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.ConstantTranslator.TypedTranslate(ExpressionConverter parent, ConstantExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, DbExpression& source, DbExpressionBinding& sourceBinding, DbExpression& lambda)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.TypedTranslate(ExpressionConverter parent, MethodCallExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, DbExpression& source, DbExpressionBinding& sourceBinding, DbExpression& lambda)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.TypedTranslate(ExpressionConverter parent, MethodCallExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.Convert()
   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClassc.<GetResultsAsync>b__a()
   at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteInTransactionAsync>d__3d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<ExecuteAsyncImplementation>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<GetResultsAsync>d__e.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Internal.LazyAsyncEnumerator`1.<FirstMoveNextAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<ForEachAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NeinLinq.Tests.DbAsyncQuery.RealTest.<AnyShouldSucceed>d__8.MoveNext() in C:\Users\Johannes\Source\nein-linq\test\NeinLinq.Tests\DbAsyncQuery\RealTest.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext()
```

**Comment by peterwurzinger** [comment]
Hi,

Is it intended, that you're mixing up two queries? In the example as well as the test you provided you do so:

```cs
    //First query
    var foo = dbContext.Set<Foo>().ToDbInjectable();

    //Second query: dbContext.Set<Bar>()
    //First query gets referenced in second line ('foo')
    var query = from bar in dbContext.Set<Bar>()
            where foo.Any(f => f.SomeInjectLambdaMethod())
            select bar;
```

```cs
    //This is the first query
    var dummies = db.Dummies.ToDbInjectable();

    //'from dummy in db.Dummies' is the second one
    //The first query also gets referenced in the second line ('dummies')
    var query = from dummy in db.Dummies
                where dummies.Any(d => d.Id < dummy.Id)
                select dummy;
```

The exception thrown by EF also indicates, that there are 2 separate queries involved.

**Comment by axelheer** [comment]
Thanks for providing a failing test! ❤️ 

Using `.ToDbInjectable()` within a sub query seems to be a problem (async or no async), although I think I'm using this somewhere already...

Using it on the outer query only works:

```csharp
[Fact]
public async Task AnyShouldSucceed()
{
    var dummies = db.Dummies;
    var query = from dummy in db.Dummies.ToDbInjectable()
                where dummies.Any(d => d.Id < dummy.Id)
                select dummy;

    var result = await query.ToListAsync();

    Assert.Equal(2, result.Count);
}
```

I'll look into it later.

**Comment by axelheer** [comment]
Okay, Entity Framework seems to require a "real" `DbSet` object for sub queries, while Entity Framework Core can handle any query-able object (however).

Exposing the actual query-able for entity framework does help (see ecb845f7febbb22449ee10f06ab544778b564c2f), but isn't nice. But I'm not giving up yet.

**Comment by peterwurzinger** [comment]
I also came around that solution when taking a deep dive - students and their spare time, you know... But while the fix resolves issues with sub queries, that are referenced as variables, it will still encounter an error when directly nested:

```cs
        [Fact]
        public void DirectlyNestedSubQueryShouldSucceed()
        {
            // TODO: make it nice
            
            var query = from dummy in db.Dummies
                where db.Dummies.ToDbInjectable().Any(d => d.Id < dummy.Id)
                //also doesn't work as '((RewriteQueryable<Dummy>)db.Dummies.ToDbInjectable()).Queryable.Any(d => d.Id < dummy.Id)'
                select dummy;

            //Produces a 'cannot translate ToDbInjectable() to ...'
            var result = query.ToList();

            Assert.Equal(2, result.Count);
        }
```

This is due to the fact, that the expression tree will contain a method cal expression to DbRewrite/ToDbInjectable/ToInjectable:
```
.Call Where(
    .Call .Constant<ObjectQuery<Dummy>>(
        ObjectQuery<Dummy>
    ).MergeAs(
        .Constant<MergeOption>(
            AppendOnly
        )
    ),
    .Call Any(
        .Call RewriteDbQueryBuilder.DbRewrite(
            .Constant<ReplacementDbQueryWrapper<Dummy>>(
                ReplacementDbQueryWrapper<Dummy>
            ).Query,
            .Constant<<RealTest+<>c__DisplayClass8_0>(
                <RealTest+<>c__DisplayClass8_0>
            ).rewriter
        ),
        $d.Id < $dummy.Id
    )
)
```

I haven't yet found an approach, which isn't exremely ugly and/or extremely error-prone. But also I don't know if that's even a valid use case.

**Comment by axelheer** [comment]
I don't think there is a really nice solution for this.

Explanation: the outer query and only the outer query parses and translates the whole expression tree. The inner query doesn't execute at all. That is by design (LINQ, not NeinLinq).

@peterwurzinger Entity Framework seems to resolve field/property/whatever expressions for their actual value (in order to check for `DbSet` objects), but "unknown" method call expressions make it cry. Entity Framework Core is a bit smarter here.

If a sub query and not the outer query uses lambda injection:
1) the lambda injection doesn't get applied anyway, since the inner query cannot do a thing
2) the outer query may or may not be able to handle the query object (Entity Framework Core is able, Entity Framework not)

I can only help with exposing the actual query. Thus, it's possible to write a simple extension method to "unwrap" queries to their original state. Please see branch `issue-11` for details.

Does that make sense?

**Comment by axelheer** [comment]
So, I did a thing.

If the outer query is an injectable (or any other NeinLinq) query too, it is now able to detect other NeinLinq queries and resolve them before passing the expression tree to the underlying query provider. Thus, the outer query must be `.ToWhatever()` too in order to make that work.

I'm currently not on windows, but this test succeeds on AppVeyor:

```csharp
[Fact]
public async Task SubQueryShouldSucceed()
{
    var dummies = db.Dummies.ToDbInjectable().Where(_ => true);

    var query = from dummy in db.Dummies.ToDbInjectable()
                where dummies.Any(d => d.Id < dummy.Id)
                select dummy;

    var result = await query.ToListAsync();

    Assert.Equal(2, result.Count);
}
```

Have a look, please (branch `issue-11`).

I'll open an PR for review, when I'm sure what I'm doing here...

**Comment by jhartmann123** [comment]
@axelheer Thanks for your quick response and sorry for my late response, didn't have the time to look into it last week.

It fixes the NotSupportedException, but somehow messes with my .Includes. Some navigational properties don't seem to be loaded - I get null references on properties that get properly loaded when not using NeinLinq on that query.

Unfortunatly when trying to write a repro/unit test for that case, the test succeeded. So maybe it's sth. on our side... I'll let you know as soon as I know more.

**Comment by axelheer** [comment]
Just let me know, when you have some details about your .Includes.

**Comment by axelheer** [comment]
Ah, the tests use the same context object for initialization and testing. Thus, all the entity objects are already there. I changed that and added two basic .Include tests.

Can you try to reproduce it, again?

**Comment by axelheer** [comment]
@jhartmann123 any further comments? Do my explanations regarding your tests make sense?

I think we've done, what can be done.
