### ISSUE TITLE
DynamicQuery.CreatePredicate doesn't work with Enums

### ISSUE THREAD

**Issue by Shaddix** [axelheer/nein-linq#19]
Throws exception:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Argument types do not match
   at System.Linq.Expressions.Expression.Constant(Object value, Type type)
   at NeinLinq.DynamicExpression.CreateConstant(ParameterExpression target, Expression selector, String value, IFormatProvider provider)
   at NeinLinq.DynamicExpression.CreateComparison(ParameterExpression target, String selector, DynamicCompare comparer, String value, IFormatProvider provider)
   at NeinLinq.DynamicQuery.CreatePredicate[T](String selector, DynamicCompare comparer, String value, IFormatProvider provider)
```

It seems to me that `DynamicExpression.CreateConverter` doesn't support enums (since enums do not have `.Parse` method).

If you don't mind, I could provide a PR with this fix

**Comment by axelheer** [comment]
A PR would be very welcome, thanks!

**Comment by axelheer** [comment]
Just merged your PR. I'm planning a new release when .NET 5.0 RC1 comes available. You can use the GitHub package feed in order to reference the most current version. Is this ok for you?

**Comment by Shaddix** [comment]
Thanks for merging, and thanks for pointing me to unlinked email (that's corrected now) :)

I think github version will work for me, could you point me to it please?

**Comment by axelheer** [comment]
Sure, here are the packages:

https://github.com/axelheer/nein-linq/packages

And here some guidance:

https://docs.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-dotnet-cli-for-use-with-github-packages
