### ISSUE TITLE
Support For Entity Framework Core 6

### ISSUE THREAD

**Issue by warappa** [axelheer/nein-linq#27]
### Issue
I installed `NeinLinq.EntityFramework.Core` `5.1.0` to a `net6.0` project using `Microsoft.EntityFrameworkCore` `6.0.0-rc.1.21452.10`. As the major versions differs I was already prepared it might not work - and so it was.

An exception was thrown, obviously due to added members in EF Core 6:
```
Unhandled exception. System.TypeLoadException: Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'NeinLinq.EntityFrameworkCore, Version=5.1.0.0, Culture=neutral, PublicKeyToken=be449d2bc6d51b0b' does not have an implementation.
   at NeinLinq.RewriteDbContextOptionsExtension.get_Info()
   at Microsoft.EntityFrameworkCore.DbContextOptions.GetHashCode()
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at ConsoleApp.TestDbContext..ctor(DbContextOptions options) in some\path\ConsoleApp\TestDbContext.cs:line 9
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at ConsoleApp.Program.Main() in some\path\Program.cs:line 60
   at ConsoleApp.Program.<Main>()
```
### Question
Can you say if and when EF Core 6 will be supported?

### Environment
.NET: .NET 6 RC1
Project: net6.0
EF Core: Microsoft.EntityFrameworkCore 6.0.0-rc.1.21452.10

**Comment by axelheer** [comment]
Thanks for the issue - hoped for no breaking change, but here it is. 🙃

I've planned at least a working build for .NET 6.0 RC1, but didn't find the time yet. You can expect something within the next few days / next week.

Stay tuned. 😎

**Comment by axelheer** [comment]
You can use the [prerelease package](https://github.com/axelheer/nein-linq/packages/180451) as well. 🤞

**Comment by warappa** [comment]
Thank you! This new package now works with EF Core 6! 🎉

Unfortunately, the global DbContext registration (`WithLambdaInjection()`) does not kick in. But I can work around that by using `ToInjectable()` or `ToEntityInjectable` on the `IQueryable<T>`.

**Comment by axelheer** [comment]
I've some basic integration tests for `WithLambdaInjection`, where it does kick in (see `EntityFrameworkCoreExtensionTest`). Thus, we have to dig deeper a little bit. Do you have a repro for this exception for me?

**Comment by warappa** [comment]
I will try to provide a repo later today!

**Comment by warappa** [comment]
Here is a gist that shows the issue:
https://gist.github.com/warappa/7b36297f604b4e5774db2e79cf5d0296

**Comment by warappa** [comment]
I just tested it and I can confirm it's fixed! Thank you for your work! 👍

**Comment by space-alien** [comment]
I am still having trouble with this - `.WithLambdaInjection()` does not seem to work, individual `.ToEntityInjectable()` calls are still required. I'm running .NET 6.0.3

**Comment by axelheer** [comment]
Can you provide a repro?

**Comment by space-alien** [comment]
I've found the problem.

I wanted to call `.WithLambdaInjection()` in the `OnConfiguring()` override in my `DbContext`.

It seems that the call to `.WithLambdaInjection()` must come after the call to `UseSqlServer()`.

Maybe worth a mention in the docs (assuming this isn't something that could be fixed)?

**Comment by axelheer** [comment]
Interesting. I'll look into that. Thanks for the research!

**Comment by axelheer** [comment]
I just added one more test `Query_WithLambdaInjectionUsingOverride_ResolvesLambdaInjection`. This seems to work... (?)

Actually, I'm doing the same within one of my projects:

```cs
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    => optionsBuilder.WithLambdaInjection();
```

Maybe there's something else?

**Comment by space-alien** [comment]
Quick thoughts off the top of my head:

 * When using `services.AddDbContext<TestWithOverrideContext>(options...)` - does the eventual call to `options.UseSqlite()` happen before or after the call to `.WithLambdaInjection()` in the override?
 * Maybe there's some provider-specific behaviour? in my case I was using SQL Server `UseSqlServer()`.

**Comment by axelheer** [comment]
- In my case, the call to `.UseSqlite()` comes first. Thus, the order doesn't change at all (I'll add one more test, which changes the order explicitly...)
- The other project of mine I checked uses SQL Server too

**Comment by axelheer** [comment]
Yeah, `.WithLambdaInjection().UseSqlite()` breaks it

**Comment by axelheer** [comment]
Okay, within the next version`RewriteDbContextOptionsExtension` will throw an error here - thx!
