### ISSUE TITLE
Issue with Moq

### ISSUE THREAD

**Issue by TheHACKATHON** [axelheer/nein-linq#40]
Hi, I have a NRE at System.Data.Entity.Internal.Linq.DbQueryVisitor.ExtractObjectQuery(Object dbQuery).
The problem appeared after the fix in 6.2.0.

Framework: net4.8
EntityFramework: 6.4.4
Moq: 4.18.4
NeinLinq: 6.2.0
NeinLinq.EntityFramework: 6.2.0

Code to reproduce
```csharp
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;
using Moq;
using Xunit;

namespace NeinLinq.Tests;

public class SomeTest
{
    [Fact]
    public void Test_Moq_WithLambdaInjection()
    {
        var items = new List<TodoItem>()
        {
            new() { Id = 1, ListId = 1 },
            new() { Id = 2, ListId = 1 }
        };

        var todoLists = new List<TodoList>()
        {
            new() { Id = 1, Items = items }
        };

        Mock<DbContext> dbContextMock = new();
        dbContextMock.Setup(dc => dc.Set<TodoList>())
            .Returns(MockDbSetCreator.GetMockDbSet(todoLists));
        dbContextMock.Setup(dc => dc.Set<TodoItem>())
            .Returns(MockDbSetCreator.GetMockDbSet(items));
        DbContext dbContext = dbContextMock.Object;

        var queryProvider = new GetTodoItemsQueryProvider();

        var query = (from list in dbContext.Set<TodoList>().ToDbInjectable()
            let item = queryProvider.GetQuery(dbContext, list.Id).FirstOrDefault()
            select item);

        var result = query.ToList();

        Assert.NotEmpty(result);

        int count = query.Count();

        Assert.NotEqual(0, count);
    }
}

public class TodoList
{
    public int Id { get; set; }

    public virtual ICollection<TodoItem> Items { get; set; } = new List<TodoItem>();
}

public class TodoItem
{
    public int Id { get; set; }

    public int ListId { get; set; }

    public virtual TodoList? List { get; set; }
}

public interface IQueryProvider<DbContext, TParam, TResult>
{
    [InjectLambda]
    IQueryable<TResult> GetQuery(DbContext context, TParam query);
}

public class GetTodoItemsQueryProvider : IQueryProvider<DbContext, int, TodoItem>
{
    [InjectLambda(nameof(GetQueryExpression))]
    public IQueryable<TodoItem> GetQuery(DbContext context, int query)
    {
        throw new NotImplementedException();
    }

    public Expression<Func<DbContext, int, IQueryable<TodoItem>>> GetQueryExpression()
    {
        return (context, query) => from todoItem in context.Set<TodoItem>()
            where todoItem.ListId == query
            select todoItem;
    }
}

public static class MockDbSetCreator
{
    public static DbSet<T> GetMockDbSet<T>(IEnumerable<T> collection) where T : class
    {
        var dbSet = new Mock<DbSet<T>>();

        dbSet.As<IQueryable<T>>().Setup(m => m.Provider)
            .Returns(collection.AsQueryable().Provider);

        dbSet.As<IQueryable<T>>().Setup(m => m.Expression)
            .Returns(collection.AsQueryable().Expression);

        dbSet.As<IQueryable<T>>().Setup(m => m.ElementType)
            .Returns(collection.AsQueryable().ElementType);

        dbSet.As<IQueryable<T>>().Setup(m => m.GetEnumerator())
            .Returns(collection.AsQueryable().GetEnumerator());

        return dbSet.Object;
    }
}

```

Stacktrace
```
System.NullReferenceException: Object reference not set to an instance of an object.

System.NullReferenceException
Object reference not set to an instance of an object.
   at System.Data.Entity.Internal.Linq.DbQueryVisitor.ExtractObjectQuery(Object dbQuery)
   at System.Data.Entity.Internal.Linq.DbQueryVisitor.CreateObjectQueryConstant(Object dbQuery)
   at System.Data.Entity.Internal.Linq.DbQueryVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitNew(NewExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NeinLinq.RewriteQueryProvider.RewriteQuery[TElement](Expression expression)
   at NeinLinq.RewriteQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NeinLinq.Tests.SomeTest.Test_Moq_WithLambdaInjection() in \TestProject1\Tests.cs:line 40
```

I believe the problem is in the MockDbSetCreator, mb I need to rewrite it some way?

**Comment by axelheer** [comment]
Through the use of `DbQueryVisitor` the internal property `InternalQuery` gets some visits:

```cs
// EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// System.Data.Entity.Internal.Linq.DbQueryVisitor
using System.Data.Entity.Core.Objects;

private static ObjectQuery ExtractObjectQuery(object dbQuery)
{
	if (dbQuery is IInternalQueryAdapter internalQueryAdapter)
	{
		return internalQueryAdapter.InternalQuery.ObjectQuery;
	}
	return null;
}

```

I honestly have no idea how to "mock" around this.
