### ISSUE TITLE
Support EFCore 9

### ISSUE THREAD

**Issue by rgroenewoudt** [axelheer/nein-linq#53]
When using Entity Framework Core 9 RC2 (https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/9.0.0-rc.2.24474.1) I'm getting the following exception:

```
System.TypeLoadException : Method 'PrecompileQuery' in type 'NeinLinq.EntityQueryCompilerAdapter`1' from assembly 'NeinLinq.EntityFrameworkCore, Version=7.1.0.0, Culture=neutral, PublicKeyToken=be449d2bc6d51b0b' does not have an implementation.
   at NeinLinq.RewriteDbContextOptionsExtension.ApplyServices(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<GetOrAdd>g__BuildServiceProvider|4_1(IDbContextOptions _, ValueTuple`2 arguments)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c.<GetOrAdd>b__4_0(IDbContextOptions contextOptions, ValueTuple`2 tuples)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
```

The exception doesn't happen when removing WithLambdaInjection() or downgrading to EFCore 8.

Considering that EFCore 9 will be released in a month, it would be nice to support it.

**Comment by rgroenewoudt** [comment]
Minimal project using SQLite to demonstrate: 
[ConsoleApp3.zip](https://github.com/user-attachments/files/17606468/ConsoleApp3.zip)

**Comment by axelheer** [comment]
#54
